import { db } from './schema';
import type { Category } from '../../features/categories/types';
import type { Product } from '../../features/inventory/types';
import type { StockTransaction } from '../../features/transactions/types';

const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-elec-001',
    code: 'ELEC',
    name: 'Electronics & Components',
    description: 'Active/passive integrated hardware and circuit components',
    color: '#1677ff',
    itemCount: 3,
    isActive: true,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'cat-raw-002',
    code: 'RAW',
    name: 'Raw Materials',
    description: 'Bulk raw manufacturing elements, cables, and copper rods',
    color: '#52c41a',
    itemCount: 2,
    isActive: true,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'cat-pack-003',
    code: 'PACK',
    name: 'Packaging & Cartons',
    description: 'Outer cartons, protective bubble rolls, and antistatic bags',
    color: '#fa8c16',
    itemCount: 2,
    isActive: true,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'cat-tool-004',
    code: 'TOOL',
    name: 'Industrial Tools',
    description: 'Calibration instruments, precision soldering, and testers',
    color: '#722ed1',
    itemCount: 1,
    isActive: true,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
];

const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'SKU-ELC-00101',
    barcode: '890123049101',
    name: 'ARM Cortex-M4 Microcontroller IC',
    description: '32-bit RISC core, 180MHz, 512KB Flash, LQFP-64',
    categoryId: 'cat-elec-001',
    categoryName: 'Electronics & Components',
    unitOfMeasure: 'PCS',
    unitCost: 3.45,
    unitPrice: 7.2,
    currentStock: 1450,
    reorderLevel: 500,
    safetyStock: 200,
    maxCapacity: 3000,
    status: 'IN_STOCK',
    warehouseLocation: 'Zone A-R04-B1',
    supplierName: 'Apex Semiconductor Corp',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'prod-002',
    sku: 'SKU-ELC-00102',
    barcode: '890123049102',
    name: 'Multilayer Ceramic Capacitor 10uF 25V',
    description: '0805 SMD X7R dielectric ceramic chip capacitor',
    categoryId: 'cat-elec-001',
    categoryName: 'Electronics & Components',
    unitOfMeasure: 'PCS',
    unitCost: 0.04,
    unitPrice: 0.12,
    currentStock: 120,
    reorderLevel: 500,
    safetyStock: 250,
    maxCapacity: 5000,
    status: 'LOW_STOCK',
    warehouseLocation: 'Zone A-R02-C3',
    supplierName: 'Murata Distribution Direct',
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'prod-003',
    sku: 'SKU-ELC-00103',
    barcode: '890123049103',
    name: 'Solid State Relay 240V 25A AC',
    description: 'Chassis mount optocoupler input high current AC relay',
    categoryId: 'cat-elec-001',
    categoryName: 'Electronics & Components',
    unitOfMeasure: 'PCS',
    unitCost: 12.8,
    unitPrice: 24.5,
    currentStock: 0,
    reorderLevel: 25,
    safetyStock: 10,
    maxCapacity: 150,
    status: 'OUT_OF_STOCK',
    warehouseLocation: 'Zone A-R09-A2',
    supplierName: 'Schneider Electric Allied',
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'prod-004',
    sku: 'SKU-RAW-00201',
    barcode: '890123049201',
    name: 'Insulated Copper Hookup Wire 18AWG',
    description: 'Stranded tinned copper wire spool, 305m black jacket',
    categoryId: 'cat-raw-002',
    categoryName: 'Raw Materials',
    unitOfMeasure: 'BOX',
    unitCost: 42.0,
    unitPrice: 78.5,
    currentStock: 18,
    reorderLevel: 20,
    safetyStock: 5,
    maxCapacity: 60,
    status: 'LOW_STOCK',
    warehouseLocation: 'Zone B-R01-D4',
    supplierName: 'Belden Wire International',
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'prod-005',
    sku: 'SKU-RAW-00202',
    barcode: '890123049202',
    name: 'Aluminum Heat Sink Extrusion 100mm',
    description: 'Anodized 6063-T5 aluminum extruded cooling profile',
    categoryId: 'cat-raw-002',
    categoryName: 'Raw Materials',
    unitOfMeasure: 'PCS',
    unitCost: 4.6,
    unitPrice: 9.8,
    currentStock: 340,
    reorderLevel: 100,
    safetyStock: 40,
    maxCapacity: 600,
    status: 'IN_STOCK',
    warehouseLocation: 'Zone B-R03-A1',
    supplierName: 'Thermal Dynamics Corp',
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'prod-006',
    sku: 'SKU-PCK-00301',
    barcode: '890123049301',
    name: 'ESD Shielding Anti-Static Bag 15x20cm',
    description: 'Zip-lock metal-in 4-layer static dissipative film pouch',
    categoryId: 'cat-pack-003',
    categoryName: 'Packaging & Cartons',
    unitOfMeasure: 'BOX',
    unitCost: 18.5,
    unitPrice: 32.0,
    currentStock: 45,
    reorderLevel: 15,
    safetyStock: 8,
    maxCapacity: 100,
    status: 'IN_STOCK',
    warehouseLocation: 'Zone C-R01-B3',
    supplierName: '3M Protective Logistics',
    createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'prod-007',
    sku: 'SKU-PCK-00302',
    barcode: '890123049302',
    name: 'Heavy Duty Fluted Shipping Carton 30x20x15',
    description: 'Double wall corrugated brown kraft shipping box pack (50s)',
    categoryId: 'cat-pack-003',
    categoryName: 'Packaging & Cartons',
    unitOfMeasure: 'BOX',
    unitCost: 28.0,
    unitPrice: 48.0,
    currentStock: 12,
    reorderLevel: 25,
    safetyStock: 10,
    maxCapacity: 80,
    status: 'LOW_STOCK',
    warehouseLocation: 'Zone C-R05-E1',
    supplierName: 'International Paper Supply',
    createdAt: new Date(Date.now() - 86400000 * 22).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'prod-008',
    sku: 'SKU-TOL-00401',
    barcode: '890123049401',
    name: 'Precision Digital Temperature Soldering Station',
    description: '70W ESD safe micro-processor controlled soldering console',
    categoryId: 'cat-tool-004',
    categoryName: 'Industrial Tools',
    unitOfMeasure: 'PCS',
    unitCost: 115.0,
    unitPrice: 185.0,
    currentStock: 8,
    reorderLevel: 10,
    safetyStock: 4,
    maxCapacity: 30,
    status: 'LOW_STOCK',
    warehouseLocation: 'Zone D-R02-C2',
    supplierName: 'Hakko Industrial Tools',
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];

const INITIAL_TRANSACTIONS: StockTransaction[] = [
  {
    id: 'tx-001',
    productId: 'prod-001',
    sku: 'SKU-ELC-00101',
    productName: 'ARM Cortex-M4 Microcontroller IC',
    type: 'INBOUND',
    quantityChange: 1000,
    quantityBefore: 450,
    quantityAfter: 1450,
    unitPrice: 3.45,
    totalValue: 3450.0,
    reason: 'Restock purchase order #PO-2026-0812',
    referenceNumber: 'PO-2026-0812',
    performedBy: 'System Warehouse Admin',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'tx-002',
    productId: 'prod-003',
    sku: 'SKU-ELC-00103',
    productName: 'Solid State Relay 240V 25A AC',
    type: 'OUTBOUND',
    quantityChange: -15,
    quantityBefore: 15,
    quantityAfter: 0,
    unitPrice: 24.5,
    totalValue: 367.5,
    reason: 'Production assembly order dispatch',
    referenceNumber: 'WO-882190',
    performedBy: 'Floor Supervisor',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const initializeDatabaseSeed = async (): Promise<void> => {
  const categoryCount = await db.categories.count();
  if (categoryCount === 0) {
    await db.categories.bulkAdd(INITIAL_CATEGORIES);
  }

  const productCount = await db.products.count();
  if (productCount === 0) {
    await db.products.bulkAdd(INITIAL_PRODUCTS);
  }

  const txCount = await db.transactions.count();
  if (txCount === 0) {
    await db.transactions.bulkAdd(INITIAL_TRANSACTIONS);
  }
};